server:
  port: 9093

spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/test_song?useSSL=false
    username: root
    password: song
    driver-class-name: com.mysql.cj.jdbc.Driver