server:
  port: 9094

spring:
  kafka:
    bootstrap-servers: localhost:9092
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/test_song?useSSL=false
    username: root
    password: song
    driver-class-name: com.mysql.cj.jdbc.Driver

app:
  kafka:
    groupId: test-group
    dlq-groupId: dlq-group
    containerFactory: kafkaListenerContainerFactory
    dlq-containerFactory: dlqKafkaListenerContainerFactory
    topics:
      basic: test-topic
      dlq-basic: test-topic.DLQ

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.kafka.core: trace
    org.springframework.transaction.interceptor: trace
    org.springframework.orm.jpa.JpaTransactionManager: DEBUG
    org.hibernate.SQL: DEBUG              # 실행되는 SQL 보기
    org.hibernate.type.descriptor.sql: TRACE

