server:
  port: 9094

spring:
  kafka:
    bootstrap-servers: localhost:9092

app:
  kafka:
    groupId: test-group
    dlq-groupId: dlq-group
    containerFactory: kafkaListenerContainerFactory
    dlq-containerFactory: dlqKafkaListenerContainerFactory
    topics:
      basic: test-topic
      dlq-basic: test-topic.DLQ
